ARCHS = arm64 arm64e
TARGET = iphone:clang::15.0
THEOS_PACKAGE_SCHEME = rootless
INSTALL_TARGET_PROCESSES = SpringBoard Safari

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = CookieHook
CookieHook_FILES = Tweak.x
CookieHook_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
