name: Build .deb
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      - name: Install tools
        run: brew install dpkg ldid make

      - name: Setup Theos
        run: |
          cd $HOME
          git clone --depth=1 https://github.com/theos/theos.git
          curl -L -o theos/bin/dm.pl https://raw.githubusercontent.com/theos/dm.pl/master/dm.pl
          chmod +x theos/bin/dm.pl

      - name: Build
        env:
          THEOS: /Users/runner/theos
          TARGET: iphone:clang::15.0
          ARCHS: arm64
        run: |
          cd CookieHook
          gmake clean package

      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: CookieHook
          path: "**/packages/*.deb"
